# run on container environment
sudo: false

language: php

notifications:
  email:
    on_success: change
    on_failure: always

php:
  - 7.0
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - phpenv config-rm xdebug.ini
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:1} == "7" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script:
  - phpunit
